### ISSUE TITLE
Actually open the chest

### ISSUE THREAD

**Issue by PostCrafter** [JustJofe/EventChest#4]
Instead of destroying the chest it would be a nice idea to actually open it.

This means that an inventory should be opened that contains the random item(s).

**Comment by JustJofe** [comment]
I'm not sure how I should understand this. Do you mean that The chest should get an BlockInventory that you can reopen everytime or do you want to only open it oncewithout destroying the chest? Because with the first method you could use the skull as a smaller and custom chest. Maybe that would be cool.

**Comment by PostCrafter** [comment]
What I meant is that instead of destroying the chest you should open it and see it's content. Once items are taken out it should get destroyed to avoid duplication bugs.

**Comment by JustJofe** [comment]
So isn't that already done with my commit that closed #3? Or am I misunderstanding something?

**Comment by PostCrafter** [comment]
This one is more of an additional idea for a feature, being able to actually claim the items by taking them out of the chest adds a nicer user experience than just magically adding them to the inventory.
I can try and extend the description later on, if it's still unclear to what I mean.
